### PR TITLE
[WIP] Initial Radio Controller

### PR DESCRIPTION
**Pull request by plauche**
- [ ] Create basic Radio Controller library
  - [ ] Parse telecommand packets
  - [ ] Recognize packet calling EnableLine method
  - [ ] Call EnableLine method on PowerManager upon receipt of EnableLine packet
  - [ ] Read in telecommand packets from external stream (Major Tom) using libuv/IO pump
  - [ ] Necessary unit + integration tests
- [ ] Create Radio Controller executable utilizing library

This PR will require another PR against kubos-vagrant adding the libuv dependency. It will also require modifying the Docker image used by CircleCI.

### CODE REVIEW

**Comment by davesims** [comment]
@plauche if you would, include a quick description/breakdown of goals on the PR.

**Comment by plauche** [comment]
[As a mission operator, I want the radio to receive and hand off incoming messages.](https://trello.com/c/xvPJEuzo/2-as-a-mission-operator-i-want-the-radio-to-receive-and-hand-off-incoming-messages)

**Comment by plauche** [comment]
@OhMeadhbh do you see any need to keep this PR around? I think at this point the work has been superseded by our Rust/GraphQL architecture.

**Comment by plauche** [comment]
This PR is way deprecated. Closing out.

**Pull request closed without merging**
